name: Tests
on: 
   push: 
     branches: [ backend ]
jobs: 
   init: 
     runs-on: ubuntu-latest
     container: node:18.10.0
     services: 
       postgres: 
         image: postgres
         env:
          POSTGRES_PASSWORD: postgres
         ports:
          - 5432:5432
     strategy:
       matrix: 
         node-version: [ 18.x ]
     steps: 
        - uses: actions/checkout@v4
        - name: Setup Node.js environment
          uses: actions/setup-node@v3
          with: 
            node-version: ${{ matrix.node-version }}
        - name: Setup environment variables
          run: |
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
            echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env
            echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
        - name: Install dependencies
          run: npm install
        - name: Building
          run: npm run build
        - name: Generate fake db
          run: node ./dist/faker.js
        - name: Prisma db
          run: npx prisma db push
        - name: Run tests
          run: npm run test 
        - name: Run end-to-end tests
          run: npm run test:e2e 